package com.fh.entity.order;

import java.util.Date;

public class OrderInsureInfo {
    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column order_insure_info.id
     *
     * @ibatorgenerated Sun Mar 04 12:17:33 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column order_insure_info.orderid
     *
     * @ibatorgenerated Sun Mar 04 12:17:33 CST 2018
     */
    private Integer orderid;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column order_insure_info.insurecode
     *
     * @ibatorgenerated Sun Mar 04 12:17:33 CST 2018
     */
    private String insurecode;

    /**
     * This field was generated by Apache iBATIS ibator.
     * This field corresponds to the database column order_insure_info.addtime
     *
     * @ibatorgenerated Sun Mar 04 12:17:33 CST 2018
     */
    private Date addtime;

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column order_insure_info.id
     *
     * @return the value of order_insure_info.id
     *
     * @ibatorgenerated Sun Mar 04 12:17:33 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column order_insure_info.id
     *
     * @param id the value for order_insure_info.id
     *
     * @ibatorgenerated Sun Mar 04 12:17:33 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column order_insure_info.orderid
     *
     * @return the value of order_insure_info.orderid
     *
     * @ibatorgenerated Sun Mar 04 12:17:33 CST 2018
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column order_insure_info.orderid
     *
     * @param orderid the value for order_insure_info.orderid
     *
     * @ibatorgenerated Sun Mar 04 12:17:33 CST 2018
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column order_insure_info.insurecode
     *
     * @return the value of order_insure_info.insurecode
     *
     * @ibatorgenerated Sun Mar 04 12:17:33 CST 2018
     */
    public String getInsurecode() {
        return insurecode;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column order_insure_info.insurecode
     *
     * @param insurecode the value for order_insure_info.insurecode
     *
     * @ibatorgenerated Sun Mar 04 12:17:33 CST 2018
     */
    public void setInsurecode(String insurecode) {
        this.insurecode = insurecode == null ? null : insurecode.trim();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method returns the value of the database column order_insure_info.addtime
     *
     * @return the value of order_insure_info.addtime
     *
     * @ibatorgenerated Sun Mar 04 12:17:33 CST 2018
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method sets the value of the database column order_insure_info.addtime
     *
     * @param addtime the value for order_insure_info.addtime
     *
     * @ibatorgenerated Sun Mar 04 12:17:33 CST 2018
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }
}